### PR TITLE
Version 0.4.2

### PR DESCRIPTION
**Pull request by B--B**
Features
                    - Added a new alternative layout
                    - Answer/Reject call with "swipe"
            Fixes
                    - If a torch button is enabled, refuse to enable the second button at the same time
                    - Stopped TimerTask when receiving a call
            Partial Fixes
                    - Incoming call screen now works 99% times in both layouts when the screen is off and the cover closed. Does not work if the screen is on and the cover closed (need to open and close the cover manually)
                    - Alternative and media widgets works for 4x1 widgets and for some 4x2 widget, but only on alternative layout
For all the other changes please see commits

### CODE REVIEW

**Comment by durka** [comment]
Hi! Thanks for this. I am testing the features on my phone. The alternative layout is a little broken for me -- the notification icons end up at the top, plus the whole layout jiggles a bit when it comes on (maybe to do with the timing of hiding the title bar?) I also need to test the swipe to answer phone calls, that sounds like fun. Once we figure out the layout issue, I'll probably ask you to squash these commits if you can, for prettier merging :)

**Comment by jumoog** [comment]
good news guys im working on native support via SW_FLIP :+1: 

Smartcover via SW_LIP already working 

https://www.youtube.com/watch?v=t1UhPEjgiws

https://www.youtube.com/watch?v=fmYmbF5DswI

**Comment by B--B** [comment]
Hi durka, you had right, i didn' t noticed icon issue, fixed in my latest commit! Regarding the jiggles problem when closing the cover i thought that was something related to notification area and the status bar because after my latest commit default layout and alternative are more or less equal, except for the notification area position, and in default layout everything is fine.. I will search in holo theme docs if there is some useful hint!

**Comment by durka** [comment]
So personally, I don't like using the standard Android notification bar because I can't see all of it through the flip cover. But I'm fine having it as an alternative layout.

Having some trouble with the call answering -- can't tell if it's working or not, maybe I just have fat fingers.

**Pull request merged**
