### PR TITLE
0.3.0-0.3.7

### PR DESCRIPTION
**Pull request by manusfreedom**
- 0.3.7
  - Features
    - Real HallMonitor support for SERRANO device
  - Fixes
    - Remove submenu on Real HallMonitor on/off
- 0.3.6
  - Features
    - Data & Time feature
    - Fix HallMonitor as System App on CM (gotosleep working): read special Readme
    - Try better touch when cover is closed (nothing change but more often call but more often call to enble it)
    - Build for more system
    - Fix licenses
- 0.3.5
  - Features
    - Possibility to choose between real Hall or simule with Proximity sensor (under Root menu)
    - Change licencing to Apache
    - Use eu.chainfire.libsuperuser in place of net.pocketmagic.android.eventinjector
    - All su access through eu.chainfire.libsuperuser.Shell
    - Removed unused library import
    - Suppress navigation bar (Softkey)
    - Remove su call from main thread
    - To test: gotosleep instead of lock if installed as SystemApp
- 0.3.0
  - Features
    - Add real Hall Event
    - Root is now a requirement
  - Remove
    - Proximity sensor use
  - Notes
    - Next version add settings to choose between Proximity sensor or Hall Event?

Signed-off-by: Manus Freedom manus@manusfreedom.com

### CODE REVIEW

**Comment by tim-devel** [comment]
Woohoo! Accept the pull!

**Comment by durka** [comment]
Hi @manusfreedom. This is a big contribution; thanks a lot! I'm working on reviewing the code. My first question is about the license. Unfortunately GPLv2 and the Apache license (which currently covers the rest of Hall Monitor) are not compatible. Is this your code that could be relicensed, or would I need to relicense Hall Monitor to accept it?

**Comment by FaxXer** [comment]
Nice work. 
You could add the Superuser permissions to AndroidManifest.xml
<-uses-permission android:name="android.permission.ACCESS_SUPERUSER" -/>     //Without the two "-"

**Comment by manusfreedom** [comment]
Sorry I did not check the license on my file I used another one as base. I don't know very well this part, my code is based on https://github.com/android/platform_system_core/blob/master/toolbox/getevent.c . So I don't know what licence change we could do.

**Comment by manusfreedom** [comment]
Please see new commits.

**Comment by durka** [comment]
Okay, great. Will look this over.

**Comment by manusfreedom** [comment]
Now able to use sleep mode instead of lock mode by using HallMonitor as System App.
Please read the special Readme.

**Comment by julred** [comment]
Can you insert the option to show the current date on the frontflip cover?

**Comment by manusfreedom** [comment]
dan2468, have you tested the 0.3.5 no System App and with Root enable and Real HallMonitor enable?

**Comment by manusfreedom** [comment]
Last commit does not fix...

**Comment by manusfreedom** [comment]
dan2468, I can get this error too. It seem a bug during copy in recovery, I don't know why, but replacing the apk the /system/app works (but use the last zip with fixed permission on file).

**Comment by manusfreedom** [comment]
jollepe: it's done.
dan2468: try to follow new instructions in special Readme (don't forget to download new files).

**Comment by dan2468** [comment]
The updated ZIP installed fine, and now the app is usable (I didn't replace the APK in /system/app). But I still have some problems:
- the app doesn't survive a reboot (it's still there in /system/app (0 0 0644); but when I open the APK I get a prompt to install it: "do you want to install an update to this built-in application"; this always fails)
- the sleep is still a lock: after the app comes up with the clock, and its timeout runs out and the display fades to black, opening the cover shows the (pattern) lock screen (this is the same in v.0.2)
- trying to use the hall sensor instead of the proximity one doesn't work (nothing happens on closing the cover)
- like in v.0.2, the touch gestures through the cover window don't register (e.g. camera, answer call)

I wonder if someone else with an S4 Mini has had a different experience…

**Comment by manusfreedom** [comment]
- I get the same problem for reboot, but I don't get a prompt to install it.
- Could you check your logs and find if you have line like:
  "F.Act.setSleepTimer(xxx) Delay set to: "
  "F.Act.close_cover(xxx) Go to sleep now."
  or
  "F.Act.setLockTimer(xxx) Delay set to: "
  "F.Act.close_cover(xxx) Locking screen now."
- Could you send content of this command (as root):
  getevent -i
- For the touch screen through the cover, I noticed too it does not work every time, I have some idea to test.

**Comment by manusfreedom** [comment]
New release 0.3.6

**Comment by dan2468** [comment]
Again, some good news: the touch gestures now register through the cover window. 

GetEvent log is on http://pastebin.com/SXVLXhxf 

Other issues:
- installing is still a pain, other than installing the ZIP in recovery and overwriting the APK in /system/app, I had to also manually copy it to /data/app/org.durka.hallmonitor-1.apk before it appeared in the app list
- hall sensor is still not having any effect, I get no setLockTimer; see http://pastebin.com/sHuzDLRN
- toggling Use Hall either way seems to revoke the administrator right of the app, I had to manually re-enable it 
- it also seems to make the app use a lot of processor power (Choreographer lines?) and SU rights requests in a short amount of time

**Comment by manusfreedom** [comment]
dan2468:
Thanks for the feedback (getevent -i is useful)
Release 0.3.7, please confirm me it fix Real HallMonitor on your device.
- Please remove everything like wrote in the special Readme: https://github.com/manusfreedom/HallMonitor/blob/master/bin/CM_SystemApp/Readme.txt
- Fixed I think
- Unable to reproduce, but I think is because you have normal and system app
- Unable to reproduce, but I think is because you have normal and system app

**Comment by VolMi** [comment]
I was reading this thread quietly and I am in the same situation as @dan2468. Same device, same issues (apart from /data/app), same `getevent -i`.

~~0.3.7 does still not provide a working `real hall` for me. I was very excited from the start but it did not work yet.~~ (edit: yes, it does)

**Comment by manusfreedom** [comment]
I don't know why it's not working.
Could you provide me logs on first init, it start with (need all VCHS-oSC logs): 
VCHS-oSC(xxx) Request root
And could you provide me logs when you set at "On" the Real HallMonitor, it start with : 
F.Act.start_service(xxx) Start service called.

**Comment by VolMi** [comment]
Uh, ah, it's working now! I wanted to reproduce the "non-working" state for logging, but now it just works!?! So cool! I have no idea why it didn't before. I made a clean install, granted root and admin rights, rebooted...
I guess you don't need logs now? :-)

Again, sooo cool! Because it is extremely reliable now. Opening or closing really fast? → Still works! Thanks a lot, manusfreedom!
I wonder why durka does not merge this or is a bit more vocal about potential issues.

~~edit: Is it really necessary to have it at /system/app or could I as well install it the classical way?~~ (edit2: Yes, at least for libGetEvent.so)

**Comment by manusfreedom** [comment]
Or Durka does not have time maybe ;)

**Comment by manusfreedom** [comment]
VolMi: Yes, at least for libGetEvent.so
No, it's only to use sleep mode instead of lock mode after "Covered lock screen timeout".

**Comment by durka** [comment]
Sorry for the delay here. I really do want to review the code, since so many things are changed here with respect to how root privileges are used and especially becoming (optionally) a system app. I hope to merge this tonight or tomorrow.

**Comment by durka** [comment]
@manusfreedom licensing question again, sorry. If GetEvent.c and GetEvent.h are based on the code from [here](https://github.com/android/platform_system_core/blob/master/toolbox), which is BSD licensed, how can you relicense it to Apache? Or is it just loosely "based" on that code.

**Comment by durka** [comment]
And a practical question. How do I set up Eclipse to build as a system app? I assume that for the F-Droid build at least I will have to disable that part anyway.

**Comment by dan2468** [comment]
@manusfreedom V.0.7 is better still.
Installation from recovery worked without the data/app/ workaround (org.durka.hallmonitor-1.apk is not there now). Hall sensor now works (even though the app crashed the very first time I enabled it; now it's fine). The app survives a reboot. The only change from before was disabling Sophos AV (but it might be coincidental). Also, before I couldn't uninstall from the UI because the option was disabled (probably because of the manual deleting and copying).

Some issues:
- toggling Use Hall either way still revokes the administrator right of the app (I had to manually re-enable it)
- after the app timeouts and fades the screen, the phone still locks instead of sleeping (for Proximity, as well as Hall, sensor)

Where should I check for the presence of libGetEvent.so? 

How to make sure I uninstall everything? (maybe this should be mentioned in the ReadMe.txt now that it's installing as a system app)

**Comment by manusfreedom** [comment]
@durka License BSD fixed... I don't like all those things... If it's an issue for you, I will try to maintain my version.
@durka To build System App : https://github.com/manusfreedom/HallMonitor/blob/master/cm_certs/build_signed_system.txt
Be careful if you use debug mode, the gotosleep will crash, because it need System App and a system signature. In debug mode the the apk directly is signed with an other certificate.
To get a working debug System App, you must in Eclipse export the compiled apk as unsigned and manually sign/align after.
@durka You don't need to remove or disable this part, the code detect if it's installed as System App or not. So it must work every time you will just be in lock mode if no System App.

**Comment by manusfreedom** [comment]
@dan2468 unable to reproduce administrator right bug
The phone still locks instead of sleeping: have you check that the time to lock in your ROM settings is not inferior to the time in HallMonitor?
libGetEvent.so is normally cleaned everywhere when you use the zip:
/cache/dalvik-cache/_org.durka.hallmonitor_
/data/anr/_org.durka.hallmonitor_
/data/app/org.durka.hallmonitor*
/data/app-lib/HallMonitor/libGetEvent.so
/data/dalvik-cache/_HallMonitor.apk_
/data/dalvik-cache/_org.durka.hallmonitor_
/system/app/HallMonitor.apk
/system/app/HallMonitor.odex
/system/lib/libGetEvent.so

Like indicated in https://github.com/manusfreedom/HallMonitor/blob/master/bin/CM_SystemApp/Readme.txt , "Go to Settings/Apps: Clear Data, Clear Cache, uninstall update and uninstall completely HallMonitor" will do the job.

**Comment by FaxXer** [comment]
Version 0.3.7 Hall Sensor works perfect on I9505 CM11. Other features like phone call accept not yet tested.
Date and time are only in version 0.3.6?

**Comment by manusfreedom** [comment]
@FaxXer Date & Time are in all version since 0.3.5.5. You must go in General Settings (Enable submenu)

**Comment by dan2468** [comment]
> The phone still locks instead of sleeping: have you check that the time to lock in your ROM settings is not inferior to the time in HallMonitor?

Yeah, I have in System Settings > Lock screen > Screen security:
-   Screen lock: Pattern
-   Automatically lock: 5 minutes after sleep
-   Power button instantly locks: ON

I'm guessing you don't have that lock-on-power option, because if I disable it, things work as expected. 

If that's the case, I should report it as a bug to CyanogenMod, because double-taping the status bar to sleep also only works when having "Power button instantly locks" OFF, otherwise it also locks the phone.

**Comment by manusfreedom** [comment]
@dan2468 It's not a bug, it's normal. Gotosleep functions is used by Power button. And it is not logical to want instant lock the screen with power button and not with the cover.

**Comment by durka** [comment]
I pulled this and @B--B's Italian translation as well. Thanks for the contribution, I will add you both to the contributors list. And I'll get a new version pushed out to F-Droid soon.

I am still confused about how exactly to build a system app, @manusfreedom. I tried running that script and signing with the keys under cm_certs, but my phone would not accepted the signed app. Are there different keys for each CM version?

**Comment by durka** [comment]
I released version 0.4.0 which includes all this as well as @B--B's translation (and one bug fix). Big thanks for these contributions (contributors have been added to the About string as well). In the future please be careful about committing generated files.

**Pull request closed without merging**
